// Generated from WHO ICD-10 2010 metadata package

export type Icd10Chapter = {
  number: string;
  title: string;
};

export type Icd10Block = {
  start: string;
  end: string;
  chapterNumber: string;
  title: string;
};

export const ICD10_CHAPTERS: readonly Icd10Chapter[] = [
  { number: '01', title: 'Certain infectious and parasitic diseases' },
  { number: '02', title: 'Neoplasms' },
  { number: '03', title: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism' },
  { number: '04', title: 'Endocrine, nutritional and metabolic diseases' },
  { number: '05', title: 'Mental and behavioural disorders' },
  { number: '06', title: 'Diseases of the nervous system' },
  { number: '07', title: 'Diseases of the eye and adnexa' },
  { number: '08', title: 'Diseases of the ear and mastoid process' },
  { number: '09', title: 'Diseases of the circulatory system' },
  { number: '10', title: 'Diseases of the respiratory system' },
  { number: '11', title: 'Diseases of the digestive system' },
  { number: '12', title: 'Diseases of the skin and subcutaneous tissue' },
  { number: '13', title: 'Diseases of the musculoskeletal system and connective tissue' },
  { number: '14', title: 'Diseases of the genitourinary system' },
  { number: '15', title: 'Pregnancy, childbirth and the puerperium' },
  { number: '16', title: 'Certain conditions originating in the perinatal period' },
  { number: '17', title: 'Congenital malformations, deformations and chromosomal abnormalities' },
  { number: '18', title: 'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified' },
  { number: '19', title: 'Injury, poisoning and certain other consequences of external causes' },
  { number: '20', title: 'External causes of morbidity and mortality' },
  { number: '21', title: 'Factors influencing health status and contact with health services' },
  { number: '22', title: 'Codes for special purposes' },
] as const;

export const ICD10_BLOCKS: readonly Icd10Block[] = [
  { start: 'A00', end: 'A09', chapterNumber: '01', title: 'Intestinal infectious diseases' },
  { start: 'A15', end: 'A19', chapterNumber: '01', title: 'Tuberculosis' },
  { start: 'A20', end: 'A28', chapterNumber: '01', title: 'Certain zoonotic bacterial diseases' },
  { start: 'A30', end: 'A49', chapterNumber: '01', title: 'Other bacterial diseases' },
  { start: 'A50', end: 'A64', chapterNumber: '01', title: 'Infections with a predominantly sexual mode of transmission' },
  { start: 'A65', end: 'A69', chapterNumber: '01', title: 'Other spirochaetal diseases' },
  { start: 'A70', end: 'A74', chapterNumber: '01', title: 'Other diseases caused by chlamydiae' },
  { start: 'A75', end: 'A79', chapterNumber: '01', title: 'Rickettsioses' },
  { start: 'A80', end: 'A89', chapterNumber: '01', title: 'Viral infections of the central nervous system' },
  { start: 'A90', end: 'A99', chapterNumber: '01', title: 'Arthropod-borne viral fevers and viral haemorrhagic fevers' },
  { start: 'B00', end: 'B09', chapterNumber: '01', title: 'Viral infections characterized by skin and mucous membrane lesions' },
  { start: 'B15', end: 'B19', chapterNumber: '01', title: 'Viral hepatitis' },
  { start: 'B20', end: 'B24', chapterNumber: '01', title: 'Human immunodeficiency virus [HIV] disease' },
  { start: 'B25', end: 'B34', chapterNumber: '01', title: 'Other viral diseases' },
  { start: 'B35', end: 'B49', chapterNumber: '01', title: 'Mycoses' },
  { start: 'B50', end: 'B64', chapterNumber: '01', title: 'Protozoal diseases' },
  { start: 'B65', end: 'B83', chapterNumber: '01', title: 'Helminthiases' },
  { start: 'B85', end: 'B89', chapterNumber: '01', title: 'Pediculosis, acariasis and other infestations' },
  { start: 'B90', end: 'B94', chapterNumber: '01', title: 'Sequelae of infectious and parasitic diseases' },
  { start: 'B95', end: 'B98', chapterNumber: '01', title: 'Bacterial, viral and other infectious agents' },
  { start: 'B99', end: 'B99', chapterNumber: '01', title: 'Other infectious diseases' },
  { start: 'C00', end: 'C14', chapterNumber: '02', title: 'Malignant neoplasms of lip, oral cavity and pharynx' },
  { start: 'C15', end: 'C26', chapterNumber: '02', title: 'Malignant neoplasms of digestive organs' },
  { start: 'C30', end: 'C39', chapterNumber: '02', title: 'Malignant neoplasms of respiratory and intrathoracic organs' },
  { start: 'C40', end: 'C41', chapterNumber: '02', title: 'Malignant neoplasms of bone and articular cartilage' },
  { start: 'C43', end: 'C44', chapterNumber: '02', title: 'Melanoma and other malignant neoplasms of skin' },
  { start: 'C45', end: 'C49', chapterNumber: '02', title: 'Malignant neoplasms of mesothelial and soft tissue' },
  { start: 'C50', end: 'C50', chapterNumber: '02', title: 'Malignant neoplasm of breast' },
  { start: 'C51', end: 'C58', chapterNumber: '02', title: 'Malignant neoplasms of female genital organs' },
  { start: 'C60', end: 'C63', chapterNumber: '02', title: 'Malignant neoplasms of male genital organs' },
  { start: 'C64', end: 'C68', chapterNumber: '02', title: 'Malignant neoplasms of urinary tract' },
  { start: 'C69', end: 'C72', chapterNumber: '02', title: 'Malignant neoplasms of eye, brain and other parts of central nervous system' },
  { start: 'C73', end: 'C75', chapterNumber: '02', title: 'Malignant neoplasms of thyroid and other endocrine glands' },
  { start: 'C76', end: 'C80', chapterNumber: '02', title: 'Malignant neoplasms of ill-defined, secondary and unspecified sites' },
  { start: 'C81', end: 'C96', chapterNumber: '02', title: 'Malignant neoplasms, stated or presumed to be primary, of lymphoid, haematopoietic and related tissue' },
  { start: 'C97', end: 'C97', chapterNumber: '02', title: 'Malignant neoplasms of independent (primary) multiple sites' },
  { start: 'D00', end: 'D09', chapterNumber: '02', title: 'In situ neoplasms' },
  { start: 'D10', end: 'D36', chapterNumber: '02', title: 'Benign neoplasms' },
  { start: 'D37', end: 'D48', chapterNumber: '02', title: 'Neoplasms of uncertain or unknown behaviour' },
  { start: 'D50', end: 'D53', chapterNumber: '03', title: 'Nutritional anaemias' },
  { start: 'D55', end: 'D59', chapterNumber: '03', title: 'Haemolytic anaemias' },
  { start: 'D60', end: 'D64', chapterNumber: '03', title: 'Aplastic and other anaemias' },
  { start: 'D65', end: 'D69', chapterNumber: '03', title: 'Coagulation defects, purpura and other haemorrhagic conditions' },
  { start: 'D70', end: 'D77', chapterNumber: '03', title: 'Other diseases of blood and blood-forming organs' },
  { start: 'D80', end: 'D89', chapterNumber: '03', title: 'Certain disorders involving the immune mechanism' },
  { start: 'E00', end: 'E07', chapterNumber: '04', title: 'Disorders of thyroid gland' },
  { start: 'E10', end: 'E14', chapterNumber: '04', title: 'Diabetes mellitus' },
  { start: 'E15', end: 'E16', chapterNumber: '04', title: 'Other disorders of glucose regulation and pancreatic internal secretion' },
  { start: 'E20', end: 'E35', chapterNumber: '04', title: 'Disorders of other endocrine glands' },
  { start: 'E40', end: 'E46', chapterNumber: '04', title: 'Malnutrition' },
  { start: 'E50', end: 'E64', chapterNumber: '04', title: 'Other nutritional deficiencies' },
  { start: 'E65', end: 'E68', chapterNumber: '04', title: 'Obesity and other hyperalimentation' },
  { start: 'E70', end: 'E90', chapterNumber: '04', title: 'Metabolic disorders' },
  { start: 'F00', end: 'F09', chapterNumber: '05', title: 'Organic, including symptomatic, mental disorders' },
  { start: 'F10', end: 'F19', chapterNumber: '05', title: 'Mental and behavioural disorders due to psychoactive substance use' },
  { start: 'F20', end: 'F29', chapterNumber: '05', title: 'Schizophrenia, schizotypal and delusional disorders' },
  { start: 'F30', end: 'F39', chapterNumber: '05', title: 'Mood [affective] disorders' },
  { start: 'F40', end: 'F48', chapterNumber: '05', title: 'Neurotic, stress-related and somatoform disorders' },
  { start: 'F50', end: 'F59', chapterNumber: '05', title: 'Behavioural syndromes associated with physiological disturbances and physical factors' },
  { start: 'F60', end: 'F69', chapterNumber: '05', title: 'Disorders of adult personality and behaviour' },
  { start: 'F70', end: 'F79', chapterNumber: '05', title: 'Mental retardation' },
  { start: 'F80', end: 'F89', chapterNumber: '05', title: 'Disorders of psychological development' },
  { start: 'F90', end: 'F98', chapterNumber: '05', title: 'Behavioural and emotional disorders with onset usually occurring in childhood and adolescence' },
  { start: 'F99', end: 'F99', chapterNumber: '05', title: 'Unspecified mental disorder' },
  { start: 'G00', end: 'G09', chapterNumber: '06', title: 'Inflammatory diseases of the central nervous system' },
  { start: 'G10', end: 'G14', chapterNumber: '06', title: 'Systemic atrophies primarily affecting the central nervous system' },
  { start: 'G20', end: 'G26', chapterNumber: '06', title: 'Extrapyramidal and movement disorders' },
  { start: 'G30', end: 'G32', chapterNumber: '06', title: 'Other degenerative diseases of the nervous system' },
  { start: 'G35', end: 'G37', chapterNumber: '06', title: 'Demyelinating diseases of the central nervous system' },
  { start: 'G40', end: 'G47', chapterNumber: '06', title: 'Episodic and paroxysmal disorders' },
  { start: 'G50', end: 'G59', chapterNumber: '06', title: 'Nerve, nerve root and plexus disorders' },
  { start: 'G60', end: 'G64', chapterNumber: '06', title: 'Polyneuropathies and other disorders of the peripheral nervous system' },
  { start: 'G70', end: 'G73', chapterNumber: '06', title: 'Diseases of myoneural junction and muscle' },
  { start: 'G80', end: 'G83', chapterNumber: '06', title: 'Cerebral palsy and other paralytic syndromes' },
  { start: 'G90', end: 'G99', chapterNumber: '06', title: 'Other disorders of the nervous system' },
  { start: 'H00', end: 'H06', chapterNumber: '07', title: 'Disorders of eyelid, lacrimal system and orbit' },
  { start: 'H10', end: 'H13', chapterNumber: '07', title: 'Disorders of conjunctiva' },
  { start: 'H15', end: 'H22', chapterNumber: '07', title: 'Disorders of sclera, cornea, iris and ciliary body' },
  { start: 'H25', end: 'H28', chapterNumber: '07', title: 'Disorders of lens' },
  { start: 'H30', end: 'H36', chapterNumber: '07', title: 'Disorders of choroid and retina' },
  { start: 'H40', end: 'H42', chapterNumber: '07', title: 'Glaucoma' },
  { start: 'H43', end: 'H45', chapterNumber: '07', title: 'Disorders of vitreous body and globe' },
  { start: 'H46', end: 'H48', chapterNumber: '07', title: 'Disorders of optic nerve and visual pathways' },
  { start: 'H49', end: 'H52', chapterNumber: '07', title: 'Disorders of ocular muscles, binocular movement, accommodation and refraction' },
  { start: 'H53', end: 'H54', chapterNumber: '07', title: 'Visual disturbances and blindness' },
  { start: 'H55', end: 'H59', chapterNumber: '07', title: 'Other disorders of eye and adnexa' },
  { start: 'H60', end: 'H62', chapterNumber: '08', title: 'Diseases of external ear' },
  { start: 'H65', end: 'H75', chapterNumber: '08', title: 'Diseases of middle ear and mastoid' },
  { start: 'H80', end: 'H83', chapterNumber: '08', title: 'Diseases of inner ear' },
  { start: 'H90', end: 'H95', chapterNumber: '08', title: 'Other disorders of ear' },
  { start: 'I00', end: 'I02', chapterNumber: '09', title: 'Acute rheumatic fever' },
  { start: 'I05', end: 'I09', chapterNumber: '09', title: 'Chronic rheumatic heart diseases' },
  { start: 'I10', end: 'I15', chapterNumber: '09', title: 'Hypertensive diseases' },
  { start: 'I20', end: 'I25', chapterNumber: '09', title: 'Ischaemic heart diseases' },
  { start: 'I26', end: 'I28', chapterNumber: '09', title: 'Pulmonary heart disease and diseases of pulmonary circulation' },
  { start: 'I30', end: 'I52', chapterNumber: '09', title: 'Other forms of heart disease' },
  { start: 'I60', end: 'I69', chapterNumber: '09', title: 'Cerebrovascular diseases' },
  { start: 'I70', end: 'I79', chapterNumber: '09', title: 'Diseases of arteries, arterioles and capillaries' },
  { start: 'I80', end: 'I89', chapterNumber: '09', title: 'Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified' },
  { start: 'I95', end: 'I99', chapterNumber: '09', title: 'Other and unspecified disorders of the circulatory system' },
  { start: 'J00', end: 'J06', chapterNumber: '10', title: 'Acute upper respiratory infections' },
  { start: 'J09', end: 'J18', chapterNumber: '10', title: 'Influenza and pneumonia' },
  { start: 'J20', end: 'J22', chapterNumber: '10', title: 'Other acute lower respiratory infections' },
  { start: 'J30', end: 'J39', chapterNumber: '10', title: 'Other diseases of upper respiratory tract' },
  { start: 'J40', end: 'J47', chapterNumber: '10', title: 'Chronic lower respiratory diseases' },
  { start: 'J60', end: 'J70', chapterNumber: '10', title: 'Lung diseases due to external agents' },
  { start: 'J80', end: 'J84', chapterNumber: '10', title: 'Other respiratory diseases principally affecting the interstitium' },
  { start: 'J85', end: 'J86', chapterNumber: '10', title: 'Suppurative and necrotic conditions of lower respiratory tract' },
  { start: 'J90', end: 'J94', chapterNumber: '10', title: 'Other diseases of pleura' },
  { start: 'J95', end: 'J99', chapterNumber: '10', title: 'Other diseases of the respiratory system' },
  { start: 'K00', end: 'K14', chapterNumber: '11', title: 'Diseases of oral cavity, salivary glands and jaws' },
  { start: 'K20', end: 'K31', chapterNumber: '11', title: 'Diseases of oesophagus, stomach and duodenum' },
  { start: 'K35', end: 'K38', chapterNumber: '11', title: 'Diseases of appendix' },
  { start: 'K40', end: 'K46', chapterNumber: '11', title: 'Hernia' },
  { start: 'K50', end: 'K52', chapterNumber: '11', title: 'Noninfective enteritis and colitis' },
  { start: 'K55', end: 'K63', chapterNumber: '11', title: 'Other diseases of intestines' },
  { start: 'K65', end: 'K67', chapterNumber: '11', title: 'Diseases of peritoneum' },
  { start: 'K70', end: 'K77', chapterNumber: '11', title: 'Diseases of liver' },
  { start: 'K80', end: 'K87', chapterNumber: '11', title: 'Disorders of gallbladder, biliary tract and pancreas' },
  { start: 'K90', end: 'K93', chapterNumber: '11', title: 'Other diseases of the digestive system' },
  { start: 'L00', end: 'L08', chapterNumber: '12', title: 'Infections of the skin and subcutaneous tissue' },
  { start: 'L10', end: 'L14', chapterNumber: '12', title: 'Bullous disorders' },
  { start: 'L20', end: 'L30', chapterNumber: '12', title: 'Dermatitis and eczema' },
  { start: 'L40', end: 'L45', chapterNumber: '12', title: 'Papulosquamous disorders' },
  { start: 'L50', end: 'L54', chapterNumber: '12', title: 'Urticaria and erythema' },
  { start: 'L55', end: 'L59', chapterNumber: '12', title: 'Radiation-related disorders of the skin and subcutaneous tissue' },
  { start: 'L60', end: 'L75', chapterNumber: '12', title: 'Disorders of skin appendages' },
  { start: 'L80', end: 'L99', chapterNumber: '12', title: 'Other disorders of the skin and subcutaneous tissue' },
  { start: 'M00', end: 'M03', chapterNumber: '13', title: 'Infectious arthropathies' },
  { start: 'M05', end: 'M14', chapterNumber: '13', title: 'Inflammatory polyarthropathies' },
  { start: 'M15', end: 'M19', chapterNumber: '13', title: 'Arthrosis' },
  { start: 'M20', end: 'M25', chapterNumber: '13', title: 'Other joint disorders' },
  { start: 'M30', end: 'M36', chapterNumber: '13', title: 'Systemic connective tissue disorders' },
  { start: 'M40', end: 'M43', chapterNumber: '13', title: 'Deforming dorsopathies' },
  { start: 'M45', end: 'M49', chapterNumber: '13', title: 'Spondylopathies' },
  { start: 'M50', end: 'M54', chapterNumber: '13', title: 'Other dorsopathies' },
  { start: 'M60', end: 'M63', chapterNumber: '13', title: 'Disorders of muscles' },
  { start: 'M65', end: 'M68', chapterNumber: '13', title: 'Disorders of synovium and tendon' },
  { start: 'M70', end: 'M79', chapterNumber: '13', title: 'Other soft tissue disorders' },
  { start: 'M80', end: 'M85', chapterNumber: '13', title: 'Disorders of bone density and structure' },
  { start: 'M86', end: 'M90', chapterNumber: '13', title: 'Other osteopathies' },
  { start: 'M91', end: 'M94', chapterNumber: '13', title: 'Chondropathies' },
  { start: 'M95', end: 'M99', chapterNumber: '13', title: 'Other disorders of the musculoskeletal system and connective tissue' },
  { start: 'N00', end: 'N08', chapterNumber: '14', title: 'Glomerular diseases' },
  { start: 'N10', end: 'N16', chapterNumber: '14', title: 'Renal tubulo-interstitial diseases' },
  { start: 'N17', end: 'N19', chapterNumber: '14', title: 'Renal failure' },
  { start: 'N20', end: 'N23', chapterNumber: '14', title: 'Urolithiasis' },
  { start: 'N25', end: 'N29', chapterNumber: '14', title: 'Other disorders of kidney and ureter' },
  { start: 'N30', end: 'N39', chapterNumber: '14', title: 'Other diseases of urinary system' },
  { start: 'N40', end: 'N51', chapterNumber: '14', title: 'Diseases of male genital organs' },
  { start: 'N60', end: 'N64', chapterNumber: '14', title: 'Disorders of breast' },
  { start: 'N70', end: 'N77', chapterNumber: '14', title: 'Inflammatory diseases of female pelvic organs' },
  { start: 'N80', end: 'N98', chapterNumber: '14', title: 'Noninflammatory disorders of female genital tract' },
  { start: 'N99', end: 'N99', chapterNumber: '14', title: 'Other disorders of the genitourinary system' },
  { start: 'O00', end: 'O08', chapterNumber: '15', title: 'Pregnancy with abortive outcome' },
  { start: 'O10', end: 'O16', chapterNumber: '15', title: 'Oedema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium' },
  { start: 'O20', end: 'O29', chapterNumber: '15', title: 'Other maternal disorders predominantly related to pregnancy' },
  { start: 'O30', end: 'O48', chapterNumber: '15', title: 'Maternal care related to the fetus and amniotic cavity and possible delivery problems' },
  { start: 'O60', end: 'O75', chapterNumber: '15', title: 'Complications of labour and delivery' },
  { start: 'O80', end: 'O84', chapterNumber: '15', title: 'Delivery' },
  { start: 'O85', end: 'O92', chapterNumber: '15', title: 'Complications predominantly related to the puerperium' },
  { start: 'O94', end: 'O99', chapterNumber: '15', title: 'Other obstetric conditions, not elsewhere classified' },
  { start: 'P00', end: 'P04', chapterNumber: '16', title: 'Fetus and newborn affected by maternal factors and by complications of pregnancy, labour and delivery' },
  { start: 'P05', end: 'P08', chapterNumber: '16', title: 'Disorders related to length of gestation and fetal growth' },
  { start: 'P10', end: 'P15', chapterNumber: '16', title: 'Birth trauma' },
  { start: 'P20', end: 'P29', chapterNumber: '16', title: 'Respiratory and cardiovascular disorders specific to the perinatal period' },
  { start: 'P35', end: 'P39', chapterNumber: '16', title: 'Infections specific to the perinatal period' },
  { start: 'P50', end: 'P61', chapterNumber: '16', title: 'Haemorrhagic and haematological disorders of fetus and newborn' },
  { start: 'P70', end: 'P74', chapterNumber: '16', title: 'Transitory endocrine and metabolic disorders specific to fetus and newborn' },
  { start: 'P75', end: 'P78', chapterNumber: '16', title: 'Digestive system disorders of fetus and newborn' },
  { start: 'P80', end: 'P83', chapterNumber: '16', title: 'Conditions involving the integument and temperature regulation of fetus and newborn' },
  { start: 'P90', end: 'P96', chapterNumber: '16', title: 'Other disorders originating in the perinatal period' },
  { start: 'Q00', end: 'Q07', chapterNumber: '17', title: 'Congenital malformations of the nervous system' },
  { start: 'Q10', end: 'Q18', chapterNumber: '17', title: 'Congenital malformations of eye, ear, face and neck' },
  { start: 'Q20', end: 'Q28', chapterNumber: '17', title: 'Congenital malformations of the circulatory system' },
  { start: 'Q30', end: 'Q34', chapterNumber: '17', title: 'Congenital malformations of the respiratory system' },
  { start: 'Q35', end: 'Q37', chapterNumber: '17', title: 'Cleft lip and cleft palate' },
  { start: 'Q38', end: 'Q45', chapterNumber: '17', title: 'Other congenital malformations of the digestive system' },
  { start: 'Q50', end: 'Q56', chapterNumber: '17', title: 'Congenital malformations of genital organs' },
  { start: 'Q60', end: 'Q64', chapterNumber: '17', title: 'Congenital malformations of the urinary system' },
  { start: 'Q65', end: 'Q79', chapterNumber: '17', title: 'Congenital malformations and deformations of the musculoskeletal system' },
  { start: 'Q80', end: 'Q89', chapterNumber: '17', title: 'Other congenital malformations' },
  { start: 'Q90', end: 'Q99', chapterNumber: '17', title: 'Chromosomal abnormalities, not elsewhere classified' },
  { start: 'R00', end: 'R09', chapterNumber: '18', title: 'Symptoms and signs involving the circulatory and respiratory systems' },
  { start: 'R10', end: 'R19', chapterNumber: '18', title: 'Symptoms and signs involving the digestive system and abdomen' },
  { start: 'R20', end: 'R23', chapterNumber: '18', title: 'Symptoms and signs involving the skin and subcutaneous tissue' },
  { start: 'R25', end: 'R29', chapterNumber: '18', title: 'Symptoms and signs involving the nervous and musculoskeletal systems' },
  { start: 'R30', end: 'R39', chapterNumber: '18', title: 'Symptoms and signs involving the urinary system' },
  { start: 'R40', end: 'R46', chapterNumber: '18', title: 'Symptoms and signs involving cognition, perception, emotional state and behaviour' },
  { start: 'R47', end: 'R49', chapterNumber: '18', title: 'Symptoms and signs involving speech and voice' },
  { start: 'R50', end: 'R69', chapterNumber: '18', title: 'General symptoms and signs' },
  { start: 'R70', end: 'R79', chapterNumber: '18', title: 'Abnormal findings on examination of blood, without diagnosis' },
  { start: 'R80', end: 'R82', chapterNumber: '18', title: 'Abnormal findings on examination of urine, without diagnosis' },
  { start: 'R83', end: 'R89', chapterNumber: '18', title: 'Abnormal findings on examination of other body fluids, substances and tissues, without diagnosis' },
  { start: 'R90', end: 'R94', chapterNumber: '18', title: 'Abnormal findings on diagnostic imaging and in function studies, without diagnosis' },
  { start: 'R95', end: 'R99', chapterNumber: '18', title: 'Ill-defined and unknown causes of mortality' },
  { start: 'S00', end: 'S09', chapterNumber: '19', title: 'Injuries to the head' },
  { start: 'S10', end: 'S19', chapterNumber: '19', title: 'Injuries to the neck' },
  { start: 'S20', end: 'S29', chapterNumber: '19', title: 'Injuries to the thorax' },
  { start: 'S30', end: 'S39', chapterNumber: '19', title: 'Injuries to the abdomen, lower back, lumbar spine and pelvis' },
  { start: 'S40', end: 'S49', chapterNumber: '19', title: 'Injuries to the shoulder and upper arm' },
  { start: 'S50', end: 'S59', chapterNumber: '19', title: 'Injuries to the elbow and forearm' },
  { start: 'S60', end: 'S69', chapterNumber: '19', title: 'Injuries to the wrist and hand' },
  { start: 'S70', end: 'S79', chapterNumber: '19', title: 'Injuries to the hip and thigh' },
  { start: 'S80', end: 'S89', chapterNumber: '19', title: 'Injuries to the knee and lower leg' },
  { start: 'S90', end: 'S99', chapterNumber: '19', title: 'Injuries to the ankle and foot' },
  { start: 'T00', end: 'T07', chapterNumber: '19', title: 'Injuries involving multiple body regions' },
  { start: 'T08', end: 'T14', chapterNumber: '19', title: 'Injuries to unspecified part of trunk, limb or body region' },
  { start: 'T15', end: 'T19', chapterNumber: '19', title: 'Effects of foreign body entering through natural orifice' },
  { start: 'T20', end: 'T25', chapterNumber: '19', title: 'Burns and corrosions of external body surface, specified by site' },
  { start: 'T26', end: 'T28', chapterNumber: '19', title: 'Burns and corrosions confined to eye and internal organs' },
  { start: 'T29', end: 'T32', chapterNumber: '19', title: 'Burns and corrosions of multiple and unspecified body regions' },
  { start: 'T33', end: 'T35', chapterNumber: '19', title: 'Frostbite' },
  { start: 'T36', end: 'T50', chapterNumber: '19', title: 'Poisoning by drugs, medicaments and biological substances' },
  { start: 'T51', end: 'T65', chapterNumber: '19', title: 'Toxic effects of substances chiefly nonmedicinal as to source' },
  { start: 'T66', end: 'T78', chapterNumber: '19', title: 'Other and unspecified effects of external causes' },
  { start: 'T79', end: 'T79', chapterNumber: '19', title: 'Certain early complications of trauma' },
  { start: 'T80', end: 'T88', chapterNumber: '19', title: 'Complications of surgical and medical care, not elsewhere classified' },
  { start: 'T90', end: 'T98', chapterNumber: '19', title: 'Sequelae of injuries, of poisoning and of other consequences of external causes' },
  { start: 'V01', end: 'V09', chapterNumber: '20', title: 'Pedestrian injured in transport accident' },
  { start: 'V10', end: 'V19', chapterNumber: '20', title: 'Pedal cyclist injured in transport accident' },
  { start: 'V20', end: 'V29', chapterNumber: '20', title: 'Motorcycle rider injured in transport accident' },
  { start: 'V30', end: 'V39', chapterNumber: '20', title: 'Occupant of three-wheeled motor vehicle injured in transport accident' },
  { start: 'V40', end: 'V49', chapterNumber: '20', title: 'Car occupant injured in transport accident' },
  { start: 'V50', end: 'V59', chapterNumber: '20', title: 'Occupant of pick-up truck or van injured in transport accident' },
  { start: 'V60', end: 'V69', chapterNumber: '20', title: 'Occupant of heavy transport vehicle injured in transport accident' },
  { start: 'V70', end: 'V79', chapterNumber: '20', title: 'Bus occupant injured in transport accident' },
  { start: 'V80', end: 'V89', chapterNumber: '20', title: 'Other land transport accidents' },
  { start: 'V90', end: 'V94', chapterNumber: '20', title: 'Water transport accidents' },
  { start: 'V95', end: 'V97', chapterNumber: '20', title: 'Air and space transport accidents' },
  { start: 'V98', end: 'V99', chapterNumber: '20', title: 'Other and unspecified transport accidents' },
  { start: 'W00', end: 'W19', chapterNumber: '20', title: 'Falls' },
  { start: 'W20', end: 'W49', chapterNumber: '20', title: 'Exposure to inanimate mechanical forces' },
  { start: 'W50', end: 'W64', chapterNumber: '20', title: 'Exposure to animate mechanical forces' },
  { start: 'W65', end: 'W74', chapterNumber: '20', title: 'Accidental drowning and submersion' },
  { start: 'W75', end: 'W84', chapterNumber: '20', title: 'Other accidental threats to breathing' },
  { start: 'W85', end: 'W99', chapterNumber: '20', title: 'Exposure to electric current, radiation and extreme ambient air temperature and pressure' },
  { start: 'X00', end: 'X09', chapterNumber: '20', title: 'Exposure to smoke, fire and flames' },
  { start: 'X10', end: 'X19', chapterNumber: '20', title: 'Contact with heat and hot substances' },
  { start: 'X20', end: 'X29', chapterNumber: '20', title: 'Contact with venomous animals and plants' },
  { start: 'X30', end: 'X39', chapterNumber: '20', title: 'Exposure to forces of nature' },
  { start: 'X40', end: 'X49', chapterNumber: '20', title: 'Accidental poisoning by and exposure to noxious substances' },
  { start: 'X50', end: 'X57', chapterNumber: '20', title: 'Overexertion, travel and privation' },
  { start: 'X58', end: 'X59', chapterNumber: '20', title: 'Accidental exposure to other and unspecified factors' },
  { start: 'X60', end: 'X84', chapterNumber: '20', title: 'Intentional self-harm' },
  { start: 'X85', end: 'Y09', chapterNumber: '20', title: 'Assault' },
  { start: 'Y10', end: 'Y34', chapterNumber: '20', title: 'Event of undetermined intent' },
  { start: 'Y35', end: 'Y36', chapterNumber: '20', title: 'Legal intervention and operations of war' },
  { start: 'Y40', end: 'Y59', chapterNumber: '20', title: 'Drugs, medicaments and biological substances causing adverse effects in therapeutic use' },
  { start: 'Y60', end: 'Y69', chapterNumber: '20', title: 'Misadventures to patients during surgical and medical care' },
  { start: 'Y70', end: 'Y82', chapterNumber: '20', title: 'Medical devices associated with adverse incidents in diagnostic and therapeutic use' },
  { start: 'Y83', end: 'Y84', chapterNumber: '20', title: 'Surgical and other medical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure' },
  { start: 'Y85', end: 'Y89', chapterNumber: '20', title: 'Sequelae of external causes of morbidity and mortality' },
  { start: 'Y90', end: 'Y98', chapterNumber: '20', title: 'Supplementary factors related to causes of morbidity and mortality classified elsewhere' },
  { start: 'Z00', end: 'Z13', chapterNumber: '21', title: 'Persons encountering health services for examination and investigation' },
  { start: 'Z20', end: 'Z29', chapterNumber: '21', title: 'Persons with potential health hazards related to communicable diseases' },
  { start: 'Z30', end: 'Z39', chapterNumber: '21', title: 'Persons encountering health services in circumstances related to reproduction' },
  { start: 'Z40', end: 'Z54', chapterNumber: '21', title: 'Persons encountering health services for specific procedures and health care' },
  { start: 'Z55', end: 'Z65', chapterNumber: '21', title: 'Persons with potential health hazards related to socioeconomic and psychosocial circumstances' },
  { start: 'Z70', end: 'Z76', chapterNumber: '21', title: 'Persons encountering health services in other circumstances' },
  { start: 'Z80', end: 'Z99', chapterNumber: '21', title: 'Persons with potential health hazards related to family and personal history and certain conditions influencing health status' },
  { start: 'U00', end: 'U49', chapterNumber: '22', title: 'Provisional assignment of new diseases of uncertain etiology' },
  { start: 'U80', end: 'U89', chapterNumber: '22', title: 'Bacterial agents resistant to antibiotics' },
] as const;
